#!/usr/bin/env python3
"""Generate and persist a synthetic campaign (ADR-0003).

    python scripts/generate_synthetic_data.py --subjects 120 --seed 42

Uses the configured DATABASE_URL. Requires a usable HMAC secret; in demo mode a
secret can be auto-generated by scripts/generate_secret.py first.
"""

from __future__ import annotations

import argparse
import secrets as _secrets

from pucv_aq_qc.config.settings import get_settings
from pucv_aq_qc.database.init_db import init_db
from pucv_aq_qc.database.session import session_scope
from pucv_aq_qc.synthetic.generator import generate_world, persist_world


def _resolve_secret() -> bytes:
    settings = get_settings()
    try:
        return settings.require_secret()
    except Exception:
        if settings.demo_mode:
            # ephemeral demo secret — fine for synthetic-only data
            return _secrets.token_bytes(32)
        raise


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--subjects", type=int, default=120)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args(argv)

    secret = _resolve_secret()
    init_db()
    world = generate_world(secret=secret, n_subjects=args.subjects, seed=args.seed)
    with session_scope() as session:
        persist_world(world, session)

    counts = world.counts()
    print(f"campaign_id={world.campaign.id}")
    for k, v in counts.items():
        print(f"{k}={v}")
    print("rut_persisted=false")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
